sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 199653
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sky_take_out
#    username: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    password: 199653